#!/usr/bin/env python3
"""Auto-name unnamed Claude Code sessions based on their content."""

import json
import os
import re
import sys
import time
import glob


# Project name mappings for well-known directories
PROJECT_ALIASES = {
    "rnb-vault": "R&B Vault",
    "afrobeats-next": "Afrobeats",
    "allegro-contracts": "Allegro",
    "allegro-ai-document-automation": "Allegro Presentation",
    "allegronordic": "Allegro Nordic",
    "tamu-plan": "Tamu Plan",
    "echoclone": "EchoClone",
    "clawd": "Clawd",
    "endre3000": "Endre3000",
    "endre3000-copy": "Endre3000 Copy",
    "infinitedesigners.com": "Infinite Designers",
    "abientottours": "Abiento Tours",
    "hus-case": "Hus Case",
    "OsloSpire": "Oslo Spire",
    "spotify-idea": "Spotify Idea",
    "allan-kisuule-portfolio-new": "Allan Portfolio",
    "Afrobeatss-firebase": "Afrobeats Firebase",
    "Iista": "Iista App",
    "listsis": "Listsis",
}


def clean_message(text):
    """Strip command tags, notification tags, and system noise from a user message."""
    # Remove XML-like tags and their content for known noise tags
    text = re.sub(r'<(local-command-caveat|command-message|command-name|task-notification|teammate-message|ide_selection)[^>]*>.*?</\1>', '', text, flags=re.DOTALL)
    # Remove any remaining XML tags
    text = re.sub(r'<[^>]+>', '', text)
    # Remove known noise phrases
    text = re.sub(r'Caveat: The messages below were generated by the user while running.*?(?=\w{3})', '', text, flags=re.DOTALL)
    text = re.sub(r'\[Request interrupted by user.*?\]', '', text)
    text = re.sub(r'Base directory for this skill:.*', '', text)
    text = re.sub(r'You are an AI coding agent managed by.*', '', text)
    text = re.sub(r'AUDIT TASK - READ ONLY, NO EDITS\s*', '', text)
    # Remove UUIDs
    text = re.sub(r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', '', text)
    # Remove markdown headers
    text = re.sub(r'^#+\s*', '', text)
    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Remove leading noise/greeting words
    text = re.sub(r'^(hei|hi|hey|hello|hie|yo|mcp|init|mcplist)\b[,.]?\s*', '', text, flags=re.IGNORECASE).strip()
    # Remove leading punctuation
    text = re.sub(r'^[❯→>⏺\-\*#]+\s*', '', text).strip()
    return text


PAPERCLIP_AGENT_RE = re.compile(
    r"^[-\s]*You are agent [0-9a-f-]+\s*(?:\(([^)]+)\))?",
    re.IGNORECASE
)


def extract_paperclip_title(messages):
    """If this looks like a Paperclip agent session, return 'Paperclip <Role>'
    (e.g., 'Paperclip AI Engineer') or None."""
    if not messages:
        return None
    m = PAPERCLIP_AGENT_RE.match(messages[0])
    if not m:
        return None
    role = m.group(1) or "Agent"
    return f"Paperclip {role.strip()}"


def extract_topic(text):
    """Extract the core topic from a message — what the user is actually asking about."""
    text = clean_message(text)
    if not text or len(text) < 5:
        return None

    # If message starts with a clear action phrase, use it
    action_starters = [
        r'^(fix|build|deploy|create|add|update|set up|configure|implement|research|review|download|install|migrate|refactor|design|optimize|clean)\s+(.{5,50})',
        r'^(use|run|check|open|deep|make|bring|look|tell|find|what|how|can|do)\s+(.{5,50})',
    ]
    for pattern in action_starters:
        m = re.match(pattern, text, re.IGNORECASE)
        if m:
            phrase = m.group(0)
            # Cut at first sentence end or quote
            phrase = re.split(r'[.!?\n""]', phrase)[0].strip()
            if len(phrase) > 50:
                phrase = phrase[:47] + "..."
            return phrase

    # Fallback: first meaningful chunk
    words = text.split()[:8]
    phrase = " ".join(words)
    phrase = re.split(r'[.!?\n""]', phrase)[0].strip()
    if len(phrase) > 50:
        phrase = phrase[:47] + "..."
    return phrase if len(phrase) > 4 else None


def extract_name(project_name, messages, cwd):
    """Generate a session name from project context + message content."""
    # Paperclip agent sessions — pull role from prompt before falling through
    # to the generic extractor (which would titlecase the UUID project dir).
    pc_title = extract_paperclip_title(messages)
    if pc_title:
        return pc_title

    # Get project alias
    proj = PROJECT_ALIASES.get(project_name, "")
    if not proj and project_name:
        # Titlecase the directory name as fallback
        proj = project_name.replace("-", " ").replace("_", " ").title()

    # Skip messages that are just system commands or empty
    real_messages = []
    for msg in messages:
        cleaned = clean_message(msg)
        if cleaned and len(cleaned) > 4:
            real_messages.append(cleaned)

    if not real_messages:
        return proj or None

    # Try to get a topic from the first real message
    topic = extract_topic(real_messages[0])

    # If first message is too short ("hei", "hi"), try second
    if (not topic or len(topic) < 8) and len(real_messages) > 1:
        topic = extract_topic(real_messages[1])

    if not topic:
        return proj or None

    # Combine project + topic
    # Avoid repeating project name if topic already contains it
    if proj and proj.lower() not in topic.lower():
        name = f"{proj}: {topic}"
    else:
        name = topic

    # Titlecase first letter
    if name and name[0].islower():
        name = name[0].upper() + name[1:]

    # Cap length
    if len(name) > 60:
        name = name[:57] + "..."

    return name


def get_session_info(jsonl_path, force_overwrite=False):
    """Get cwd, custom-title status, and first N user messages from a session.

    With force_overwrite=True, continues scanning past a custom-title entry so
    we can still collect messages for re-naming (caller decides whether to
    actually overwrite)."""
    cwd = ""
    has_title = False
    messages = []

    try:
        with open(jsonl_path, "r") as f:
            for line in f:
                try:
                    data = json.loads(line)

                    if data.get("type") == "custom-title":
                        has_title = True
                        if not force_overwrite:
                            return cwd, has_title, messages  # Early exit

                    if not cwd and data.get("cwd"):
                        cwd = data["cwd"]

                    if data.get("type") == "user":
                        msg = data.get("message", {})
                        if msg.get("role") == "user":
                            content = msg.get("content", "")
                            text = None
                            if isinstance(content, str) and content.strip():
                                text = content.strip()
                            elif isinstance(content, list):
                                for c in content:
                                    if isinstance(c, dict) and c.get("type") == "text":
                                        text = c["text"].strip()
                                        break
                            if text:
                                messages.append(text[:300])
                                if len(messages) >= 3:
                                    return cwd, has_title, messages
                except (json.JSONDecodeError, KeyError):
                    continue
    except Exception:
        pass

    return cwd, has_title, messages


def main():
    force = "--force" in sys.argv
    overwrite = "--overwrite" in sys.argv

    home = os.path.expanduser("~")
    base = os.path.join(home, ".claude", "projects")

    unnamed = []
    named_count = 0
    skipped_count = 0
    overwrite_count = 0

    BOLD = "\033[1m"
    DIM = "\033[2m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    CYAN = "\033[36m"
    RESET = "\033[0m"

    for jsonl_path in glob.glob(f"{base}/**/*.jsonl", recursive=True):
        cwd, has_title, messages = get_session_info(jsonl_path, force_overwrite=overwrite)

        if has_title and not overwrite:
            skipped_count += 1
            continue

        if has_title and overwrite:
            overwrite_count += 1

        if not messages:
            continue

        project_name = os.path.basename(cwd) if cwd else ""
        name = extract_name(project_name, messages, cwd)

        if not name:
            continue

        session_id = os.path.basename(jsonl_path).replace(".jsonl", "")
        preview = clean_message(messages[0])[:70] if messages else ""

        unnamed.append({
            "path": jsonl_path,
            "id": session_id,
            "name": name,
            "preview": preview,
        })

    if not unnamed:
        print(f"\n{GREEN}All sessions already have names.{RESET} ({skipped_count} named)")
        return

    print(f"\n{BOLD}Auto-naming sessions{RESET}")
    if overwrite:
        print(f"  Already named (will overwrite): {overwrite_count}")
    else:
        print(f"  Already named (skipped): {skipped_count}")
    print(f"  To name: {len(unnamed)}")
    print()

    for s in unnamed[:40]:
        print(f"  {CYAN}{s['id'][:12]}...{RESET} -> {GREEN}{s['name']}{RESET}")
        if s['preview']:
            print(f"               {DIM}{s['preview'][:65]}{RESET}")
    if len(unnamed) > 40:
        print(f"  {DIM}... and {len(unnamed) - 40} more{RESET}")
    print()

    if not force:
        print(f"{YELLOW}Dry run.{RESET} Run with {BOLD}--force{RESET} to write names.")
        return

    # Write names
    for s in unnamed:
        try:
            # Skip sessions that look live — Claude Code may still be writing
            # to them. Appending our custom-title line could corrupt a
            # mid-flight write or race with the client.
            if time.time() - os.path.getmtime(s["path"]) < 60:
                print(f"  Skipped (live): {s['id'][:12]}...")
                continue

            entry = json.dumps({
                "type": "custom-title",
                "customTitle": s["name"],
                "sessionId": s["id"],
            })

            # JSONL rule: exactly one newline between records. Check the
            # file's last byte — if it already ends with "\n", we just
            # append entry + "\n". If not, prepend a newline. Avoids the
            # blank "\n\n{entry}" pattern that confuses line-based parsers.
            needs_leading_newline = False
            try:
                with open(s["path"], "rb") as rf:
                    rf.seek(-1, 2)  # last byte
                    last = rf.read(1)
                    if last != b"\n":
                        needs_leading_newline = True
            except OSError:
                pass  # empty file — no leading newline needed

            with open(s["path"], "a") as f:
                prefix = "\n" if needs_leading_newline else ""
                f.write(prefix + entry + "\n")
            named_count += 1
        except Exception as e:
            print(f"  Error naming {s['id']}: {e}")

    print(f"\n{GREEN}Named {named_count} sessions.{RESET}")


if __name__ == "__main__":
    main()
